discipl/discipl-law-reg

- test/.gitignore
- test/flint-example-awb.json
- test/index.spec.js
- test/validate.sh
Just useful for development.
Extracts acts, facts and duties from a json file and compares them to the defined ones.
> Validation script

- package-lock.json
- package.json
- src/index.js
- test/index.spec.js
- tool/output.json
> Parse with pegjs

- .travis.yml
- package-lock.json
- package.json
- src/index.js
- test/index.spec.js
In addition to refactoring the fact logic, I worked out some other technical dept as well:
- Updated and pinned dependencies, added npm audit to ci
- Removed commented code and placeholder functions (revert d92cf13) if you need them back.
- Added javascript documentation and typings to a lot of functions.
This PR fixes #16
> Refactoring fact logic

- package.json
- src/index.js
- test/index.spec.js
Needed to implement https://github.com/discipl/ComplianceByDesign/issues/73
> Provide act links and actDetails

- package.json
- src/index.js
- test/index.spec.js
Provides the law-reg functionality for https://github.com/discipl/ComplianceByDesign/issues/105
> Introducing getActiveDuties

- test/flint-example-lerarenbeurs.json
These changes fixed https://github.com/discipl/ComplianceByDesign/issues/99
> Updates to the model, additional withdrawal reason

- package.json
- src/index.js
- test/index.spec.js
- test/lerarenbeurs-scenarios.spec.js
> Bugfix for act that was shown as available but should not be

- package.json
- src/index.js
- test/index.spec.js
Needed to properly implement https://github.com/discipl/ComplianceByDesign/issues/149
> Add support for async factresolver

- package.json
- src/index.js
- test/index.spec.js
Fundamental work to be able to do https://github.com/discipl/ComplianceByDesign/issues/156
> Validation of the model

- package-lock.json
- package.json
- src/index.js
- test/flint-example-lerarenbeurs.json
This is to explore an editor-strategy to easily edit the boolean expressions in json
> Allow pre-parsed expressions in models

- package-lock.json
- package.json
- src/index.js
- src/modelValidator.js
- test/flint-example-lerarenbeurs.json
- test/modelValidator.spec.js
Models will now accept arrays of create/terminate conditions, rather than ;-separated strings.
Fixes #60
> Refactor create and terminate

- package-lock.json
- package.json
- src/index.js
- src/modelValidator.js
- test/ANLB-scenarios.spec.js
- test/ANLb.flint.json
- test/index.spec.js
- test/lerarenbeurs-scenarios.spec.js
- test/modelValidator.spec.js
- test/scenario-util.js
Follow-up PR to #67 
Closes #68
> ANLb integration test

- package.json
- src/index.js
- src/util.js
- test/ANLB-scenarios.spec.js
- test/index.spec.js
- test/lerarenbeurs-scenarios.spec.js
This PR builds on #70, because I need both to update the demo
> Fix async factresolver bug

- package.json
- src/util.js
- test/ANLB-scenarios.spec.js
- test/lerarenbeurs-scenarios.spec.js
Exactly what it says on the tin
> Upgrade util to main package such that it can be used in the demo

- package.json
- src/index.js
- test/index.spec.js
This PR adds LESS_THAN, EQUAL, SUM, PRODUCT, MIN and MAX operations.
It does not take into account lists, just a list of facts that each resolve to a number.
> Simple mathematics

- package-lock.json
- package.json
- src/big_util.js
- src/index.js
- src/util.js
- test/big_util.spec.js
- test/index.spec.js
- test/lerarenbeurs-scenarios.spec.js
> Use big.js for arbitrary precision arithmatic to prevent rounding errors

- package-lock.json
- package.json
- src/index.js
- test/index.spec.js
> Adding literal expressions

- src/modelValidator.js
- test/modelValidator.spec.js
> Implemented handling errors from jsonc-parcer

- src/modelValidator.js
- test/modelValidator.spec.js
> Fixed bug where a reference used as an operand is not validated

- package.json
- src/index.js
- test/index.spec.js
Introduces the 'explain' function which returns details on why an action can or cannot be taken
> Explanation

- package-lock.json
- package.json
- src/index.js
- test/index.spec.js
This PR remove the `flintItem` from the context and closes #99
> Remove flintItem from context in favour of myself

- README.md
- doc/vision.md
- package-lock.json
- package.json
- src/index.js
> Fixed some typos

- package-lock.json
- package.json
- src/index.js
- src/util.js
- test/index.spec.js
Added ability to set one fact to multiple actors like: 
```
{ '[ingezetene]': ['ingezetene1', 'ingezetene2'] }
```
> Multi same type actors

- package-lock.json
- package.json
- src/index.js
- test/index.spec.js
> Fixed a bug with projection expressions returning undefined and LESS_THAN and EQUALS expressions

- src/expressions/equalExpressionChecker.js
- src/expressions/lessThanExpressionChecker.js
- src/expressions/listExpressionChecker.js
- src/expressions/maxExpressionChecker.js
- src/expressions/minExpressionChecker.js
- src/expressions/productExpressionChecker.js
- src/expressions/projectionExpressionChecker.js
- src/expressions/sumExpressionChecker.js
- src/services/factChecker.js
- src/typedefs.js
- src/utils/big_util.js
- test/logging.js
- test/math-expression.spec.js
- test/projection-expression.spec.js
- Makes it so at least ambtenaar doesn't show `<<subsidie aanvraag intrekken>>` as potentially available from #127 
- Fixed some issues with less_than expressions
- Refactored min and max to use BigUtil
> Partial fix for actor projections and getPotentialActs

- package-lock.json
- package.json
- src/expressions/orExpressionChecker.js
- test/math-expression.spec.js
> Numbers in or expressions
